name: Build and Push Docker Image

on:
  push:
    branches: ["main"]  # Trigger on pushes to main branch

env:
  IMAGE_NAME: femi/techcloak  # Replace with your Docker Hub repo name

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Extract metadata (tags, labels) for Docker image
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      # Step 4: Build and push Docker image
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .                # Path to Dockerfile location (root dir)
          push: true                # Push after building
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy to test
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-cv0ncpogph6c738pmtug   # Enter your render service ID
          api-key: rnd_VmQJ50o6AWfdo2RB0vmrjOpur53F  # Enter your render api-key
          wait-for-success: true
